# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               R0ok_
tagline:             'leh amateur sysadmin'
description:         '<em>for category in ${categories[*]}; do echo $category; done</em>'
url:                 https://oguya.github.io
#url:                 http://0.0.0.0:4000
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Oguya
  url:               http://google.com/+JamesOguya
  email:             oguyajames@gmail.com

# Custom vars
version:             1.0.0
repo:                https://github.com/oguya/oguya.github.io
